$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: random_forest_training_pipeline
experiment_name: price-classification-training
description: Training Pipeline to predict used car prices using Random Forrest Tree classifier

inputs:
  input:
    type: uri_file
    path: azureml:used-car-price-data@latest

outputs:
  train_data:
  test_data:
  model_info_output_path:

settings:
  default_datastore: azureml:workspaceblobstore
  default_compute: azureml:test-cluster
  continue_on_step_failure: false

jobs:
  prep_data:
    name: prep_data
    display_name: prep-data
    code: ../../../data-science/src
    command: >-
      python prep.py 
      --data ${{inputs.data}} 
      --train_data ${{outputs.train_data}}
      --test_data ${{outputs.test_data}}
    environment: azureml:used-car-env@latest
    inputs:
      data: ${{parent.inputs.input}}
    outputs:
      train_data: ${{parent.outputs.train_data}}
      test_data: ${{parent.outputs.test_data}}

  sweep_step:
    name: sweep_job
    display_name: sweep-job
    type: sweep
    inputs:
      train_data: ${{parent.jobs.prep_data.outputs.train_data}}
      test_data: ${{parent.jobs.prep_data.outputs.test_data}}
    outputs:
      model_output:
        type: mlflow_model
    sampling_algorithm: random
    trial: ./train.yml  # Refers to a separate command component
    search_space:
      n_estimators:
        type: choice
        values: [10, 20, 30, 50]
      max_depth:
        type: choice
        values: [1,3,5,10]
    objective:
      goal: minimize
      primary_metric: MSE
    limits:
      max_total_trials: 20
      max_concurrent_trials: 10
      timeout: 7200


  register_model:
    name: register_model
    display_name: register-model
    code: ../../../data-science/src
    command: >-
      python register.py 
      --model ${{inputs.model_name}} 
    environment: azureml:used-car-env@latest
    inputs:
      model_name: "random_forest_model"
      model_path: ${{parent.jobs.sweep_step.outputs.model_output}}
    outputs:
      model_info_output_path: ${{parent.outputs.model_info_output_path}}
